---
startDelaySeconds: 20
lowercaseOutputName: true
lowercaseOutputLabelNames: true

rules:
- pattern: ".*"

# - pattern: 'java.lang<type=Threading><>(TotalStartedThreadCount|ThreadCount)'
#   name: java_lang_threading_$1
#   type: GAUGE