global:
  scrape_interval: 60s 
  evaluation_interval: 60s 

  external_labels:
      monitor: 'JeMPI_prom'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'JeMPI_api'
    dns_sd_configs:
      - names:
          - 'JeMPI_api'
        type: 'A'
        port: 50001
  - job_name: 'JeMPI_linker'
    dns_sd_configs:
      - names:
          - 'JeMPI_linker'
        type: 'A'
        port: 50011
  - job_name: 'JeMPI_controller'
    dns_sd_configs:
      - names:
          - 'JeMPI_controller'
        type: 'A'
        port: 50021
  - job_name: 'JeMPI_em'
    dns_sd_configs:
      - names:
          - 'JeMPI_em'
        type: 'A'
        port: 91
  - job_name: 'JeMPI_kafka-1'
    dns_sd_configs:
      - names:
          - 'JeMPI_kafka-1'
        type: 'A'
        port: 1234
  - job_name: 'JeMPI_kafka-2'
    dns_sd_configs:
      - names:
          - 'JeMPI_kafka-2'
        type: 'A'
        port: 1235
  - job_name: 'JeMPI_kafka-3'
    dns_sd_configs:
      - names:
          - 'JeMPI_kafka-3'
        type: 'A'
        port: 1236
  - job_name: 'JeMPI_dgraph_zero'
    dns_sd_configs:
      - names:
          - 'JeMPI_zero'
        type: 'A'
        port: 6080
  - job_name: 'JeMPI_dgraph_alpha1'
    dns_sd_configs:
      - names:
          - 'JeMPI_alpha1'
        type: 'A'
        port: 8080
  - job_name: 'JeMPI_dgraph_alpha2'
    dns_sd_configs:
      - names:
          - 'JeMPI_alpha2'
        type: 'A'
        port: 8081
  - job_name: 'JeMPI_dgraph_alpha3'
    dns_sd_configs:
      - names:
          - 'JeMPI_alpha3'
        type: 'A'
        port: 8082
  